### ISSUE TITLE
Css를 활용한 디자인 개선

### ISSUE THREAD

**Issue by kimgh06** [BSSM-Online-teacher-judge/TOJ-client#16]
margin이나 top 속성을 사용해 header부분과 main 부분을 조금 떨어지게 하였으면 좋겠습니다.
그리고 버튼 부분에 background-color와 border 속성을 사용해 윤곽선을 없앤뒤 배경색상을 추가하고,
text-align 속성을 사용해 버튼을 가운데로 오는 것이 보기가 좋습니다.
마지막으로 버튼 크기 좀 키워주시기 바랍니다.

**Comment by leekyukin** [comment]
완성본 아닙니다 ㅎㅎㅎㅎㅎㅎㅎㅎㅎㅎㅎㅎㅎㅎㅎㅎㅎㅎㅎㅎ

**Comment by leekyukin** [comment]
"css" 쪽으로 참으로 박식하시네요 ㅎㅎㅎ

**Comment by jsm8109jsm** [comment]
@kimgh06  여기 "css"를 활용한 디자인 개선 완료되었습니다!!!!

**Comment by kimgh06** [comment]
혹시 저한테 디스코드로 친추 보내 주실 수 있나요?
어떻게 사용하는지 확인하고 싶습니다.
Discord : 구름미각#0067

**Comment by kimgh06** [comment]
혹시 저한테 디스코드로 친추 보내 주실 수 있나요?
어떻게 사용하는지 확인하고 싶습니다.
Discord : 구름미각#0067

**Comment by jsm8109jsm** [comment]
@kimgh06 혹시 어떤 부분이 궁금하신 건가요?

**Comment by jsm8109jsm** [comment]
이 프로

**Comment by kimgh06** [comment]
Css를 적용했다는 말씀을 듣고, 깃허브에 있는 TOJ-Client문서를 클론하여 서버를 열려고 했습니다.
하지만 타입스크립트와 리액트를 같이 사용했을 경우 서버를 어떻게 여는지 몰라서 화면을 확인을 하지 못했습니다.
따라서, 서버를 어떻게 여는지에 대해 알려주시면 감사하겠습니다.

**Comment by kimgh06** [comment]
> Css를 적용했다는 말씀을 듣고, 깃허브에 있는 TOJ-Client문서를 클론하여 서버를 열려고 했습니다. 하지만 타입스크립트와 리액트를 같이 사용했을 경우 서버를 어떻게 여는지 몰라서 화면을 확인을 하지 못했습니다. 따라서, 서버를 어떻게 여는지에 대해 알려주시면 감사하겠습니다.

이러한 것은 개인적으로 이야기 하는 게 나을 것 같아서 연락처를 넣었습니다.

**Comment by jsm8109jsm** [comment]
서버는 스프링부트 사용하고 있고, TOJ-server 레파지토리를 git clone 해서 사용하시면 될 것 같네요.
만약 클라이언트만 보고 싶으시다면 기존 리액트와 같이 npm start 하시면 됩니다.

**Comment by jsm8109jsm** [comment]
솔직히 처음 쓰신 글을 보고, 조금 화가 났었습니다. 뭔가 비꼬는 것 같았거든요. 근데 지금 보니 순수하게 저희 프로젝트에 호기심이 생겨서 그러신 것 같아요. 저와 제 친구가 공격적인 어조로 답변한 것에 대해 사과드리고 싶네요.

아직 미완성이라, 배포는 따로 하지 않았습니다. 나중에 완성하고 나서 배포하면 그때 보셔도 될 것 같네요.

**Comment by leekyukin** [comment]
저는 네이버 채용 담당자분이 저희 채용하려고 인성 테스트하는 줄 알았습니다;;
